### ISSUE TITLE
layout not packing correctly unless resized

### ISSUE THREAD

**Issue by jaytrovare** [scarletsky/react-masonry-layout#6]
I just want to say I love this component, but when using infinite scroll it seems that its not packing or updating the bricks.js instance correctly causing the new items to stack up. For some reason though if i resize the window to 768px or 1024px after it stacks it causes it to reload normally

heres a video:
https://www.youtube.com/watch?v=n2h86FDW3l8&feature=youtu.be

(this is using next.js btw)

Thanks in advance!

**Comment by scarletsky** [comment]
Maybe this is because your wrapper's size is dynamical, and when it add to the dom tree, the images do not load completely, so the wrapper's size is zero, and it influence the bricks.js calculation.
